"""data table

Revision ID: 9838908f4a41
Revises: 
Create Date: 2021-01-11 18:56:37.827104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9838908f4a41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_geo', sa.String(length=345), nullable=True),
    sa.Column('street_search', sa.String(length=345), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_data_street_geo'), 'app_data', ['street_geo'], unique=False)
    op.create_index(op.f('ix_app_data_street_search'), 'app_data', ['street_search'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_data_street_search'), table_name='app_data')
    op.drop_index(op.f('ix_app_data_street_geo'), table_name='app_data')
    op.drop_table('app_data')
    # ### end Alembic commands ###
